In [3]:
print("My ML journey has started")


My ML journey has started


In [4]:
import numpy as np

# строки = квартиры
# столбцы = [площадь, комнаты, этаж]
X = np.array([
    [30, 1, 2],
    [45, 2, 5],
    [60, 3, 7],
    [25, 1, 1],
    [80, 4, 10]
])

X

array([[30,  1,  2],
       [45,  2,  5],
       [60,  3,  7],
       [25,  1,  1],
       [80,  4, 10]])

In [5]:
import numpy as np
np.__version__

'2.4.2'

In [6]:
X.shape

(5, 3)

In [7]:
import numpy as np

# средняя площадь
np.mean(X[:, 0])

np.float64(48.0)

In [8]:
# максимальный этаж
np.max(X[:, 2])

np.int64(10)

In [9]:
# средние значения по каждому признаку (по столбцам)
np.mean(X, axis=0)

array([48. ,  2.2,  5. ])

In [10]:
# Z-score стандартизация вручную (как StandardScaler)
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)

X_z = (X - X_mean) / X_std
X_z

array([[-0.893325  , -1.02899151, -0.91287093],
       [-0.1488875 , -0.17149859,  0.        ],
       [ 0.59555   ,  0.68599434,  0.60858062],
       [-1.14147083, -1.02899151, -1.21716124],
       [ 1.58813333,  1.54348727,  1.52145155]])

In [11]:
np.mean(X_z, axis=0), np.std(X_z, axis=0)

(array([-4.44089210e-17, -1.77635684e-16,  0.00000000e+00]),
 array([1., 1., 1.]))

In [14]:
np.max(X[:, 0])

np.int64(80)

In [13]:
np.max(X_z[:, 0])

np.float64(1.5881333343534882)